<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        $cars = [
            [
                'nama_model' => 'Agya GR Sport',
                'kategori' => 'hatchback',
                'tag' => null,
                'deskripsi_singkat' => 'Hatchback lincah dengan sentuhan sporty GR untuk mobilitas perkotaan.',
                'harga' => 237_500_000,
                'stok' => 45,
                'horsepower' => 88,
                'estimasi_konsumsi' => '20 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.2L 3-Silinder DOHC Dual VVT-i',
                'kapasitas_mesin' => '1197 cc',
                'tenaga_maksimum' => '88 hp @ 6000 rpm',
                'torsi_maksimum' => '113 Nm @ 4200 rpm',
                'transmisi' => 'CVT 7-Percepatan',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 12.8s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Camry Hybrid',
                'kategori' => 'sedan',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'Keandalan legendaris yang didefinisikan ulang untuk perjalanan komuter modern.',
                'harga' => 937_400_000,
                'stok' => 12,
                'horsepower' => 169,
                'estimasi_konsumsi' => '32 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.5L 4-Silinder Hybrid Dynamic Force',
                'kapasitas_mesin' => '2487 cc',
                'tenaga_maksimum' => '169 hp @ 5700 rpm',
                'torsi_maksimum' => '221 Nm @ 3600-5200 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Multi-link',
                'akselerasi' => '0-100 km/h dalam 8.3s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Fortuner VRZ',
                'kategori' => 'suv',
                'tag' => null,
                'deskripsi_singkat' => 'SUV tangguh dengan karakter maskulin, andal di segala medan.',
                'harga' => 617_700_000,
                'stok' => 28,
                'horsepower' => 204,
                'estimasi_konsumsi' => '12 Est.',
                'drivetrain' => '4x4',
                'tipe_mesin' => '2.8L 4-Silinder Turbo Diesel',
                'kapasitas_mesin' => '2755 cc',
                'tenaga_maksimum' => '204 hp @ 3400 rpm',
                'torsi_maksimum' => '500 Nm @ 1600-2800 rpm',
                'transmisi' => 'Otomatis 6-Percepatan',
                'suspensi' => 'Double Wishbone / 4-Link Rigid',
                'akselerasi' => '0-100 km/h dalam 9.6s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Innova Zenix',
                'kategori' => 'mpv',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'MPV keluarga premium dengan kenyamanan dan efisiensi kelas atas.',
                'harga' => 425_600_000,
                'stok' => 85,
                'horsepower' => 183,
                'estimasi_konsumsi' => '23 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.0L 4-Silinder Hybrid Dynamic Force',
                'kapasitas_mesin' => '1987 cc',
                'tenaga_maksimum' => '183 hp @ 6000 rpm',
                'torsi_maksimum' => '188 Nm @ 4400-5200 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 9.9s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Corolla Altis',
                'kategori' => 'sedan',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'Keandalan legendaris yang didefinisikan ulang untuk perjalanan komuter modern.',
                'harga' => 528_500_000,
                'stok' => 32,
                'horsepower' => 169,
                'estimasi_konsumsi' => '32 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.0L Hybrid Dynamic Force',
                'kapasitas_mesin' => '1987 cc',
                'tenaga_maksimum' => '169 hp @ 6000 rpm',
                'torsi_maksimum' => '190 Nm @ 4400-5200 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Multi-link',
                'akselerasi' => '0-100 km/h dalam 9.2s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Raize GR Sport',
                'kategori' => 'suv',
                'tag' => 'GR Sport',
                'deskripsi_singkat' => 'Compact agility with aggressive aerodynamic styling.',
                'harga' => 254_500_000,
                'stok' => 40,
                'horsepower' => 97,
                'estimasi_konsumsi' => '18 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.2L Turbo 3-Silinder',
                'kapasitas_mesin' => '1198 cc',
                'tenaga_maksimum' => '97 hp @ 6000 rpm',
                'torsi_maksimum' => '140 Nm @ 4400 rpm',
                'transmisi' => 'CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 11.5s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
        ];

        foreach ($cars as $car) {
            Car::updateOrCreate(['nama_model' => $car['nama_model']], $car);
        }
    }
}
