<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\GrCar;
use Illuminate\Database\Seeder;

class ToyotaDummySeeder extends Seeder
{
    public function run(): void
    {
        $cars = [
            [
                'nama_model' => 'New Calya',
                'kategori' => 'mpv',
                'tag' => 'Value',
                'deskripsi_singkat' => 'MPV entry-level Toyota yang praktis, irit, dan cocok untuk keluarga muda.',
                'harga' => 170_700_000,
                'stok' => 60,
                'horsepower' => 88,
                'estimasi_konsumsi' => '20 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.2L 4-Silinder DOHC Dual VVT-i',
                'kapasitas_mesin' => '1197 cc',
                'tenaga_maksimum' => '88 hp @ 6000 rpm',
                'torsi_maksimum' => '113 Nm @ 4200 rpm',
                'transmisi' => 'Manual 5-Percepatan / D-CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 13.6s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Avanza',
                'kategori' => 'mpv',
                'tag' => 'Best Seller',
                'deskripsi_singkat' => 'MPV serbaguna dengan kabin lega untuk kebutuhan harian dan perjalanan keluarga.',
                'harga' => 255_800_000,
                'stok' => 74,
                'horsepower' => 104,
                'estimasi_konsumsi' => '18 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.5L 4-Silinder Dual VVT-i',
                'kapasitas_mesin' => '1496 cc',
                'tenaga_maksimum' => '104 hp @ 6000 rpm',
                'torsi_maksimum' => '137 Nm @ 4200 rpm',
                'transmisi' => 'Manual 5-Percepatan / CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 12.5s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'New Veloz Hybrid EV',
                'kategori' => 'mpv',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'MPV modern dengan nuansa premium, kabin luas, dan efisiensi hybrid untuk keluarga.',
                'harga' => 330_000_000,
                'stok' => 38,
                'horsepower' => 111,
                'estimasi_konsumsi' => '24 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.5L Hybrid Series Parallel',
                'kapasitas_mesin' => '1490 cc',
                'tenaga_maksimum' => '111 hp @ 6000 rpm',
                'torsi_maksimum' => '141 Nm @ 4200 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 10.9s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'New Kijang Innova Zenix Hybrid EV',
                'kategori' => 'mpv',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'MPV keluarga yang lebih premium dengan efisiensi tinggi dan kenyamanan kelas atas.',
                'harga' => 473_600_000,
                'stok' => 29,
                'horsepower' => 183,
                'estimasi_konsumsi' => '23 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.0L Hybrid Dynamic Force',
                'kapasitas_mesin' => '1987 cc',
                'tenaga_maksimum' => '183 hp @ 6000 rpm',
                'torsi_maksimum' => '188 Nm @ 4400-5200 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 9.8s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'New Vellfire Hybrid EV',
                'kategori' => 'mpv',
                'tag' => 'Luxury',
                'deskripsi_singkat' => 'MPV mewah dengan kenyamanan kabin tinggi dan efisiensi hybrid untuk perjalanan premium.',
                'harga' => 1_872_800_000,
                'stok' => 7,
                'horsepower' => 190,
                'estimasi_konsumsi' => '19 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.5L Hybrid Dynamic Force',
                'kapasitas_mesin' => '2487 cc',
                'tenaga_maksimum' => '190 hp @ 6000 rpm',
                'torsi_maksimum' => '236 Nm @ 4300-4500 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Double Wishbone',
                'akselerasi' => '0-100 km/h dalam 9.5s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Agya GR Sport',
                'kategori' => 'hatchback',
                'tag' => 'GR Sport',
                'deskripsi_singkat' => 'Hatchback kompak dengan tampilan sporty dan karakter lincah untuk penggunaan harian.',
                'harga' => 238_100_000,
                'stok' => 45,
                'horsepower' => 88,
                'estimasi_konsumsi' => '21 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.2L 3-Silinder DOHC Dual VVT-i',
                'kapasitas_mesin' => '1197 cc',
                'tenaga_maksimum' => '88 hp @ 6000 rpm',
                'torsi_maksimum' => '113 Nm @ 4200 rpm',
                'transmisi' => 'CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 12.9s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Raize GR Sport',
                'kategori' => 'suv',
                'tag' => 'GR Sport',
                'deskripsi_singkat' => 'SUV kompak yang gesit, modern, dan cocok untuk mobilitas perkotaan.',
                'harga' => 292_100_000,
                'stok' => 41,
                'horsepower' => 97,
                'estimasi_konsumsi' => '18 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.0L Turbo 3-Silinder',
                'kapasitas_mesin' => '996 cc',
                'tenaga_maksimum' => '97 hp @ 6000 rpm',
                'torsi_maksimum' => '140 Nm @ 2400-4000 rpm',
                'transmisi' => 'D-CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 11.4s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Rush GR Sport',
                'kategori' => 'suv',
                'tag' => 'GR Sport',
                'deskripsi_singkat' => 'SUV 7-penumpang dengan ground clearance tinggi dan karakter tangguh untuk keluarga aktif.',
                'harga' => 314_600_000,
                'stok' => 36,
                'horsepower' => 104,
                'estimasi_konsumsi' => '15 Est.',
                'drivetrain' => 'RWD',
                'tipe_mesin' => '1.5L 4-Silinder Dual VVT-i',
                'kapasitas_mesin' => '1496 cc',
                'tenaga_maksimum' => '104 hp @ 6000 rpm',
                'torsi_maksimum' => '136 Nm @ 4200 rpm',
                'transmisi' => 'Automatic 4-Percepatan',
                'suspensi' => 'Double Wishbone / 5-Link Lateral Rod',
                'akselerasi' => '0-100 km/h dalam 13.1s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'Yaris Cross Hybrid EV',
                'kategori' => 'suv',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'SUV urban dengan efisiensi hybrid, kabin nyaman, dan fitur keselamatan lengkap.',
                'harga' => 449_900_000,
                'stok' => 26,
                'horsepower' => 111,
                'estimasi_konsumsi' => '25 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '1.5L Hybrid Dynamic Force',
                'kapasitas_mesin' => '1490 cc',
                'tenaga_maksimum' => '111 hp @ 6000 rpm',
                'torsi_maksimum' => '141 Nm @ 4000 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Torsion Beam',
                'akselerasi' => '0-100 km/h dalam 10.7s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'New Corolla Altis Hybrid EV',
                'kategori' => 'sedan',
                'tag' => 'Hybrid',
                'deskripsi_singkat' => 'Sedan elegan dengan kenyamanan berkendara premium dan teknologi hybrid yang efisien.',
                'harga' => 646_600_000,
                'stok' => 19,
                'horsepower' => 169,
                'estimasi_konsumsi' => '32 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.0L Hybrid Dynamic Force',
                'kapasitas_mesin' => '1987 cc',
                'tenaga_maksimum' => '169 hp @ 6000 rpm',
                'torsi_maksimum' => '190 Nm @ 4400-5200 rpm',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Multi-link',
                'akselerasi' => '0-100 km/h dalam 9.1s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'New Camry Hybrid EV',
                'kategori' => 'sedan',
                'tag' => 'Premium Hybrid',
                'deskripsi_singkat' => 'Sedan flagship Toyota dengan rasa berkendara halus, mewah, dan sangat efisien.',
                'harga' => 937_400_000,
                'stok' => 11,
                'horsepower' => 218,
                'estimasi_konsumsi' => '30 Est.',
                'drivetrain' => 'FWD',
                'tipe_mesin' => '2.5L Hybrid Dynamic Force',
                'kapasitas_mesin' => '2487 cc',
                'tenaga_maksimum' => '218 hp system output',
                'torsi_maksimum' => '221 Nm + motor listrik',
                'transmisi' => 'e-CVT',
                'suspensi' => 'MacPherson Strut / Multi-link',
                'akselerasi' => '0-100 km/h dalam 8.3s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
        ];

        foreach ($cars as $car) {
            Car::updateOrCreate(['nama_model' => $car['nama_model']], $car);
        }

        $grCars = [
            [
                'nama_model' => 'GR Yaris',
                'tag' => 'New',
                'deskripsi_singkat' => 'Sports car rally-bred dengan performa eksplosif dan penggerak AWD khas GR.',
                'harga' => 799_000_000,
                'stok' => 14,
                'horsepower' => 261,
                'drivetrain' => 'GR-FOUR AWD',
                'spec_chip_1' => '1.6L 3-Cyl Turbo',
                'spec_chip_2' => 'GR-FOUR AWD',
                'tipe_mesin' => '1.6L 3-Silinder Turbo G16E-GTS',
                'kapasitas_mesin' => '1618 cc',
                'tenaga_maksimum' => '261 hp @ 6500 rpm',
                'torsi_maksimum' => '360 Nm @ 3000-4600 rpm',
                'transmisi' => 'Manual 6-Percepatan',
                'suspensi' => 'MacPherson Strut / Double Wishbone',
                'akselerasi' => '0-100 km/h dalam 5.2s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'GR Supra',
                'tag' => 'Performance',
                'deskripsi_singkat' => 'Sports coupe ikonik Toyota dengan karakter balap dan tenaga besar di putaran bawah.',
                'harga' => 1_379_900_000,
                'stok' => 4,
                'horsepower' => 382,
                'drivetrain' => 'RWD',
                'spec_chip_1' => '3.0L Inline-6 Turbo',
                'spec_chip_2' => 'RWD',
                'tipe_mesin' => '3.0L Twin-Scroll Single Turbo Inline 6-Cylinder',
                'kapasitas_mesin' => '2998 cc',
                'tenaga_maksimum' => '382 hp @ 5800-6500 rpm',
                'torsi_maksimum' => '500 Nm @ 1800-5000 rpm',
                'transmisi' => 'Otomatis 8-Percepatan',
                'suspensi' => 'Adaptive Variable Sport (AVS) System',
                'akselerasi' => '0-100 km/h dalam 3.9s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'GR 86',
                'tag' => null,
                'deskripsi_singkat' => 'Coupe ringan dan lincah yang menonjolkan feedback kemudi serta fun-to-drive murni.',
                'harga' => 950_000_000,
                'stok' => 9,
                'horsepower' => 228,
                'drivetrain' => 'RWD',
                'spec_chip_1' => '2.4L Boxer NA',
                'spec_chip_2' => 'Lightweight RWD',
                'tipe_mesin' => '2.4L Boxer 4-Silinder NA',
                'kapasitas_mesin' => '2387 cc',
                'tenaga_maksimum' => '228 hp @ 7000 rpm',
                'torsi_maksimum' => '250 Nm @ 3700 rpm',
                'transmisi' => 'Manual 6-Percepatan',
                'suspensi' => 'MacPherson Strut / Double Wishbone',
                'akselerasi' => '0-100 km/h dalam 6.3s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
            [
                'nama_model' => 'GR Corolla',
                'tag' => 'New',
                'deskripsi_singkat' => 'Hot hatch GR dengan AWD dan mesin turbo kecil bertenaga besar untuk karakter agresif.',
                'harga' => 1_250_000_000,
                'stok' => 6,
                'horsepower' => 300,
                'drivetrain' => 'AWD',
                'spec_chip_1' => '1.6L 3-Cyl Turbo',
                'spec_chip_2' => 'GR-FOUR AWD',
                'tipe_mesin' => '1.6L 3-Silinder Turbo G16E-GTS',
                'kapasitas_mesin' => '1618 cc',
                'tenaga_maksimum' => '300 hp @ 6500 rpm',
                'torsi_maksimum' => '400 Nm @ 3000 rpm',
                'transmisi' => 'Manual 6-Percepatan',
                'suspensi' => 'MacPherson Strut / Multi-link',
                'akselerasi' => '0-100 km/h dalam 4.9s',
                'gambar_utama' => null,
                'galeri' => [],
            ],
        ];

        foreach ($grCars as $grCar) {
            GrCar::updateOrCreate(['nama_model' => $grCar['nama_model']], $grCar);
        }
    }
}
